[project]
name = "lifecycle-hooks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.93.0",
    "openai-agents>=0.1.0",
    "pydantic>=2.11.7",
    "pydentic>=0.0.1.dev3",
    "python-dotenv>=1.1.1",
]
